app:
  name: "ipaas-mono"
  version: "0.1.0"
  deployment: "dev"
  apiUrl: "http://localhost:8082"
  frontendUrl: "http://localhost:5174/"
  baseDefaultDomain: "apps.cargoway.cloud"
  tempFolderPath: "./tmp"

rabbitmq:
  requestQueue: request-test
  responseQueue: response-test

http:
  port: "8082"

logger:
  level: "debug"
  type: "text"

database:
  driver: "mongo"

jwt:
  duration: "10h"

gitProvider:
  provider: "github"
  redirectUri: "/api/v1/oauth/callback"
  callbackUri: "/api/v1/oauth/callback"

traefik:
  errorPageServiceNamespace: "ipaas"
  errorPageServiceName: "whoami-service"

k8s:
  kubeConfigPath: "/home/vano/.kube/config"
  cpuResource: "200m"
  memoryResource: "512Mi"
  registryUrl: "registry.cargoway.cloud"

logProvider:
  provider: "mock"
  baseUrl: "http://localhost:8090"
