app:
  name: "ipaas-mono"
  version: "0.1.0"
  deployment: "dev"
  apiUrl: "http://api.ipaas.localhost"
  frontendUrl: "http://ipaas.localhost"
  baseDefaultDomain: "ipaasapp.localhost"

rabbitmq:
  requestQueue: request-test
  responseQueue: response-test

http:
  port: "8082"

logger:
  level: "debug"
  type: "text"

database:
  driver: "mongo"

jwt:
  duration: "10h"

gitProvider:
  provider: "github"
  redirectUri: "/api/v1/oauth/callback"
  callbackUri: "/api/v1/oauth/callback"

traefik:
  apiBaseUrl: "http://traefik.dev.localhost"