app:
  name: "ipaas-mono"
  version: "0.1.0"
  deployment: "dev"

rabbitmq:
  requestQueue: request-test
  responseQueue: response-test

http:
  port: "8082"

logger:
  level: "debug"
  type: "text"

database:
  driver: "mongo"

jwt:
  duration: "10h"

oauth:
  provider: "github"
  redirectUri: "http://localhost:8082/api/v1/oauth/callback"
  callbackUri: "http://localhost:8082/api/v1/oauth/callback"
