http:
  routers:
    to-traefikAPI:
      rule: Host(`traefik.dev.localhost`)
      service: api@internal
      middlewares:
        - auth
    to-ipaas:
      rule: Host(`ipaas.localhost`)
      service: ipaas
  services:
    ipaas:
      loadBalancer:
        servers:
        - url: "http://127.0.0.1:8082/"
  middlewares:
    auth:
      basicAuth:
        users:
          - dev:$apr1$uFmhs8yR$cIWu5L3.ksIaSn443vQ8C/
          - ipaas:$apr1$aSmb0F/X$Lh3VpA8/zhRBdlvKd3JHE/
